// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocAR-WJ4sFnHzDogDb7o5V_jMYMIOqgw',
    appId: '1:910504344799:web:db88a3a4b31c931ec3bd6a',
    messagingSenderId: '910504344799',
    projectId: 'gps-miniproject2',
    authDomain: 'gps-miniproject2.firebaseapp.com',
    storageBucket: 'gps-miniproject2.appspot.com',
    measurementId: 'G-7ES0D48CRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Z2zE276vqY4C2B_1u2RXVFLAdAyZ0bU',
    appId: '1:910504344799:android:a5c67870af8d47d5c3bd6a',
    messagingSenderId: '910504344799',
    projectId: 'gps-miniproject2',
    storageBucket: 'gps-miniproject2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0oO4BCwrHEjuhQi1m_WBupoJh4hbxRqg',
    appId: '1:910504344799:ios:0cff80a0bc14a4b0c3bd6a',
    messagingSenderId: '910504344799',
    projectId: 'gps-miniproject2',
    storageBucket: 'gps-miniproject2.appspot.com',
    iosBundleId: 'com.example.fontendMiniproject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0oO4BCwrHEjuhQi1m_WBupoJh4hbxRqg',
    appId: '1:910504344799:ios:0cff80a0bc14a4b0c3bd6a',
    messagingSenderId: '910504344799',
    projectId: 'gps-miniproject2',
    storageBucket: 'gps-miniproject2.appspot.com',
    iosBundleId: 'com.example.fontendMiniproject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAocAR-WJ4sFnHzDogDb7o5V_jMYMIOqgw',
    appId: '1:910504344799:web:6506409a3940bbb3c3bd6a',
    messagingSenderId: '910504344799',
    projectId: 'gps-miniproject2',
    authDomain: 'gps-miniproject2.firebaseapp.com',
    storageBucket: 'gps-miniproject2.appspot.com',
    measurementId: 'G-K5D56YVW72',
  );
}
